"""
tests/debug_sod_full_system.py

Full-system debug runner for Send-on-Delta (SoD) under FDMA-style channel budget.

This debug follows the project output convention:

    tests/results/<debug_name>/YYYYMMDD_HHMMSS/

By default:

    tests/results/debug_sod_full_system/YYYYMMDD_HHMMSS/

It saves:
- a copy of the YAML config used, or the generated default config;
- metadata JSON;
- arrays NPZ;
- figures in the configured formats.

Purpose
-------
Visualize and diagnose the SoD branch with the physically correct chain:

    X random
    -> filter_periodic(...)
    -> remove DC
    -> peak-to-peak adjustment
    -> SoD acquisition WITHOUT quantization, to determine event_count
    -> compute M_SoD from channel capacity and event_count
    -> SoD acquisition WITH quantization using M_SoD
    -> received/dequantized SoD event samples
    -> dense SoD reconstruction
    -> sinc_filter(...) reconstruction
    -> MSE and plots

Important budget rule
---------------------
For adaptive/event-driven methods, the number of bins is NOT copied from the
Benchmark Approach. Instead, it is computed from the available channel budget and
the actual number of transmitted objects.

For SoD, if K_s events are generated by sensor s in one period and R_s bits are
available, then:

    K_s * fields_per_event * log2(M_SoD,s) <= R_s

where:

    fields_per_event = 2, if event time + amplitude are transmitted
    fields_per_event = 1, if amplitude-only optimistic mode is used

The feasible M_SoD,s is computed by:

    sfc.core.theory.compute_M_sod_per_sensor(...)

Core usage
----------
This file uses core functions/classes for the actual system operations:

    sfc.core.filters.filter_periodic
    sfc.core.filters.sinc_filter
    sfc.core.acquisition.sod.SoDAcquisitionCore
    sfc.core.system_parameters.build_derived_system_parameters
    sfc.core.mac.fdma.FDMACore
    sfc.core.theory.compute_M_sod_per_sensor

Local debug logic introduced here
---------------------------------
Only lightweight debug utilities are implemented locally:
- YAML loading and output-directory management;
- random source generation;
- DC removal using the same period convention used in the project;
- peak-to-peak scaling;
- plotting and metadata serialization.

No channel-capacity formula is reimplemented here. FDMA budget quantities are
obtained through core modules.

Usage
-----
Python console:

    from tests.debug_sod_full_system import run_debug_sod_full_system

    out = run_debug_sod_full_system(
        config_path="tests/configs/sod_full_system_debug.yaml",
        show_plots=True
    )

or without YAML:

    out = run_debug_sod_full_system(show_plots=True)

Terminal:

    python tests/debug_sod_full_system.py

or:

    python tests/debug_sod_full_system.py --config tests/configs/sod_full_system_debug.yaml --show
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict, Optional

import matplotlib.pyplot as plt
import numpy as np
import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sfc.core.acquisition.sod import SoDAcquisitionCore
from sfc.core.filters import filter_periodic, sinc_filter
from sfc.core.mac.fdma import FDMACore
from sfc.core.system_parameters import build_derived_system_parameters
from sfc.core.theory import compute_M_sod_per_sensor


DEFAULT_CONFIG_PATH = (
    PROJECT_ROOT
    / "tests"
    / "configs"
    / "sod_full_system_debug.yaml"
)

BASE_NAME = "sod_full_system_debug"


# =============================================================================
# CONFIG / OUTPUT
# =============================================================================

def default_config() -> Dict[str, Any]:
    """
    Default debug config used when config_path is None or the default config file
    does not exist.
    """
    return {
        "system": {
            "S": 1,
            "B": 2500.0,
            "P": 1.0,
            "N0": 0.01,
            "R": 12,
            "L": 4,
            "bandwidth_allocation": None,
        },
        "signal": {
            "distribution": "uniform",
            "W": 10.0,
            "tau": 1.0,
            "Tt": 0.001,
            "peak_to_peak": 2.0,
            "n_periods": 1,
        },
        "quantization": {
            "force_power_of_two": False,
            "rounding_mode": "floor",
        },
        "sod": {
            "threshold": 0.1,
            "transmit_event_times": True,
            "reconstruction_mode": "zero_order_hold",
            "initial_event": True,
            "periodic_replicas": 10,
        },
        "debug": {
            "seed": 42,
            "sensor_index": 0,
        },
        "output": {
            "base_dir": "tests/results",
            "figure_dir": "debug_sod_full_system",
            "formats": {
                "figure": ["png", "pdf"],
            },
            "save_config_copy": True,
            "save_metadata": True,
            "save_arrays": True,
            "save_plot": True,
        },
    }


def load_yaml_config(config_path: Optional[str]) -> Dict[str, Any]:
    """
    Load YAML config. If config_path is None, return default config.
    """
    if config_path is None:
        return default_config()

    path = Path(config_path)

    if not path.is_file():
        if path == DEFAULT_CONFIG_PATH:
            return default_config()

        raise FileNotFoundError("Config file not found: {}".format(path))

    with path.open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    if cfg is None:
        raise ValueError("YAML config is empty: {}".format(path))

    return cfg


def ensure_output_section(cfg: Dict[str, Any]) -> Dict[str, Any]:
    """
    Ensure output section exists and follows the tests/results convention.
    """
    if "output" not in cfg:
        cfg["output"] = {}

    cfg["output"].setdefault("base_dir", "tests/results")
    cfg["output"].setdefault("figure_dir", "debug_sod_full_system")

    if "formats" not in cfg["output"]:
        cfg["output"]["formats"] = {"figure": ["png", "pdf"]}

    cfg["output"].setdefault("save_config_copy", True)
    cfg["output"].setdefault("save_metadata", True)
    cfg["output"].setdefault("save_arrays", True)
    cfg["output"].setdefault("save_plot", True)

    return cfg


def prepare_output_dir(cfg: Dict[str, Any]) -> tuple:
    """
    Prepare timestamped output directory:

        output.base_dir / output.figure_dir / YYYYMMDD_HHMMSS/
    """
    output_cfg = cfg["output"]
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    output_dir = os.path.join(
        output_cfg["base_dir"],
        output_cfg["figure_dir"],
        timestamp,
    )

    os.makedirs(output_dir, exist_ok=True)

    return output_dir, timestamp


def get_git_commit() -> str:
    """
    Return current git commit hash, or 'unknown'.
    """
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=str(PROJECT_ROOT),
            stderr=subprocess.DEVNULL,
        ).decode("utf-8").strip()
    except Exception:
        return "unknown"


def save_config_copy_or_dump(
    cfg: Dict[str, Any],
    config_path: Optional[str],
    output_dir: str,
    timestamp: str,
) -> str:
    """
    Save the config used for this run.

    If config_path exists, copy it. Otherwise, dump the in-memory default config.
    """
    dst = os.path.join(output_dir, "{}_{}.yaml".format(BASE_NAME, timestamp))

    if config_path is not None and Path(config_path).is_file():
        shutil.copyfile(config_path, dst)
    else:
        with open(dst, "w", encoding="utf-8") as f:
            yaml.dump(cfg, f, sort_keys=False)

    return dst


def save_metadata(metadata: Dict[str, Any], output_dir: str, timestamp: str) -> str:
    """
    Save metadata JSON.
    """
    path = os.path.join(
        output_dir,
        "{}_metadata_{}.json".format(BASE_NAME, timestamp),
    )

    with open(path, "w", encoding="utf-8") as f:
        json.dump(_make_json_safe(metadata), f, indent=2)

    return path


def save_npz_payload(output_dir: str, timestamp: str, **arrays) -> str:
    """
    Save arrays to NPZ.
    """
    path = os.path.join(
        output_dir,
        "{}_arrays_{}.npz".format(BASE_NAME, timestamp),
    )

    np.savez(path, **arrays)

    return path


def figure_formats(cfg: Dict[str, Any]) -> list:
    """
    Resolve figure formats from config.
    """
    formats = cfg.get("output", {}).get("formats", {}).get("figure", None)

    if formats is None:
        formats = cfg.get("output", {}).get("formats", {}).get("plot", ["png", "pdf"])

    return list(formats)


def save_figure(fig, output_dir: str, base_name: str, formats: list) -> Dict[str, str]:
    """
    Save figure in requested formats.

    Figures are not closed here so that show_plots=True can display them at the
    end. The caller closes all figures when interactive display is disabled.
    """
    generated = {}

    for fmt in formats:
        path = os.path.join(output_dir, "{}.{}".format(base_name, fmt))

        if fmt == "png":
            fig.savefig(path, dpi=300, bbox_inches="tight")
        elif fmt == "pdf":
            fig.savefig(path, bbox_inches="tight")
        else:
            raise ValueError("Unsupported figure format: {}".format(fmt))

        generated[fmt] = path

    return generated


# =============================================================================
# LOCAL DEBUG HELPERS
# =============================================================================

def _generate_random_signal(n_time: int, distribution: str, rng: np.random.Generator) -> np.ndarray:
    """
    Generate random source signal for debug.
    """
    distribution = str(distribution).lower()

    if distribution == "uniform":
        return rng.uniform(-1.0, 1.0, size=n_time)

    if distribution == "gaussian":
        return rng.normal(0.0, 1.0, size=n_time)

    raise ValueError("signal.distribution must be 'uniform' or 'gaussian'.")


def _remove_dc_one_period(x: np.ndarray, Tt: float, tau: float) -> tuple:
    """
    Remove DC using the same discrete-period convention used elsewhere:

        dc = Tt * sum(x) / tau
    """
    x = np.asarray(x, dtype=float)
    dc = float(Tt * np.sum(x) / tau)
    return x - dc, dc


def _adjust_peak_to_peak(x: np.ndarray, peak_to_peak: float) -> tuple:
    """
    Scale signal to requested peak-to-peak value.
    """
    x = np.asarray(x, dtype=float)
    peak_to_peak = float(peak_to_peak)

    if peak_to_peak == 0:
        return np.array(x, copy=True), 1.0

    current_p2p = float(np.max(x) - np.min(x))

    if np.isclose(current_p2p, 0.0):
        return np.array(x, copy=True), 1.0

    scale = peak_to_peak / current_p2p
    return x * scale, scale


def _compute_mse(x_ref: np.ndarray, x_hat: np.ndarray) -> float:
    """
    Compute MSE.
    """
    x_ref = np.asarray(x_ref, dtype=float)
    x_hat = np.asarray(x_hat, dtype=float)

    if x_ref.shape != x_hat.shape:
        raise ValueError(
            "Shape mismatch: x_ref.shape={} and x_hat.shape={}".format(
                x_ref.shape,
                x_hat.shape,
            )
        )

    return float(np.mean((x_ref - x_hat) ** 2))


def _make_json_safe(obj: Any):
    """
    Convert object to JSON-safe representation.
    """
    if isinstance(obj, dict):
        return {str(k): _make_json_safe(v) for k, v in obj.items()}

    if isinstance(obj, list):
        return [_make_json_safe(v) for v in obj]

    if isinstance(obj, tuple):
        return [_make_json_safe(v) for v in obj]

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    if isinstance(obj, np.integer):
        return int(obj)

    if isinstance(obj, np.floating):
        if np.isfinite(obj):
            return float(obj)
        return None

    if isinstance(obj, float):
        if np.isfinite(obj):
            return obj
        return None

    return obj


# =============================================================================
# SIGNAL GENERATION
# =============================================================================

def generate_random_filtered_dc_p2p_signals(
    cfg: Dict[str, Any],
    rng: np.random.Generator,
    params,
    t: np.ndarray,
) -> Dict[str, np.ndarray]:
    """
    Generate one random filtered signal per sensor.

    Chain:
        random X
        -> filter_periodic
        -> remove DC
        -> adjust peak-to-peak
    """
    n_time = len(t)
    S = int(params.S)

    distribution = cfg["signal"].get("distribution", "uniform")
    W = float(cfg["signal"].get("W", params.W))
    Tt = float(cfg["signal"]["Tt"])
    tau = float(params.tau)
    peak_to_peak = float(cfg["signal"].get("peak_to_peak", 0.0))

    x_raw = np.zeros((n_time, S), dtype=float)
    x_filtered = np.zeros((n_time, S), dtype=float)
    x_no_dc = np.zeros((n_time, S), dtype=float)
    x_ref = np.zeros((n_time, S), dtype=float)

    dc_values = np.zeros(S, dtype=float)
    p2p_scales = np.ones(S, dtype=float)

    for s in range(S):
        x_raw[:, s] = _generate_random_signal(
            n_time=n_time,
            distribution=distribution,
            rng=rng,
        )

        x_filtered[:, s] = filter_periodic(
            x_raw[:, s],
            W=W,
            Tt=Tt,
            tau=tau,
        )

        x_no_dc[:, s], dc_values[s] = _remove_dc_one_period(
            x_filtered[:, s],
            Tt=Tt,
            tau=tau,
        )

        x_ref[:, s], p2p_scales[s] = _adjust_peak_to_peak(
            x_no_dc[:, s],
            peak_to_peak=peak_to_peak,
        )

    return {
        "x_raw": x_raw,
        "x_filtered": x_filtered,
        "x_no_dc": x_no_dc,
        "x_ref": x_ref,
        "dc_values": dc_values,
        "p2p_scales": p2p_scales,
    }


# =============================================================================
# PLOTS
# =============================================================================

def plot_signal_and_events(
    t,
    x_ref,
    event_times_tx,
    event_values_tx,
    event_times_rx,
    event_values_rx,
    sensor_index,
    output_dir,
    timestamp,
    formats,
):
    """
    Plot reference signal and SoD event samples.
    """
    fig, ax = plt.subplots(figsize=(10.0, 5.2))

    ax.plot(
        t,
        x_ref,
        linewidth=2.0,
        label="x(t) filtered, DC removed, P2P adjusted",
    )

    ax.plot(
        event_times_tx,
        event_values_tx,
        "o",
        markersize=5,
        label="SoD collected samples",
    )

    ax.plot(
        event_times_rx,
        event_values_rx,
        "x",
        markersize=6,
        label="SoD received/dequantized samples",
    )

    ax.set_title("SoD samples | sensor {}".format(sensor_index))
    ax.set_xlabel("t")
    ax.set_ylabel("Amplitude")
    ax.grid(True, linestyle=":", linewidth=0.7)
    ax.legend(loc="best", frameon=True)

    fig.tight_layout()

    return {
        "signal_events_{}".format(fmt): path
        for fmt, path in save_figure(
            fig,
            output_dir,
            "{}_signal_events_{}".format(BASE_NAME, timestamp),
            formats,
        ).items()
    }


def plot_reconstruction(
    t,
    x_ref,
    x_hat_sod,
    x_hat_sinc,
    mse_sod,
    mse_sinc,
    output_dir,
    timestamp,
    formats,
):
    """
    Plot SoD dense reconstruction and sinc_filter reconstruction.
    """
    fig, ax = plt.subplots(figsize=(10.0, 5.2))

    ax.plot(
        t,
        x_ref,
        linewidth=2.0,
        label="x(t) reference",
    )

    ax.plot(
        t,
        x_hat_sod,
        linestyle="--",
        linewidth=1.7,
        label="SoD dense reconstruction",
    )

    ax.plot(
        t,
        x_hat_sinc,
        linestyle="-.",
        linewidth=1.5,
        label="sinc_filter after SoD reconstruction",
    )

    ax.set_title(
        "SoD reconstruction | MSE dense={:.3e}, MSE sinc={:.3e}".format(
            mse_sod,
            mse_sinc,
        )
    )
    ax.set_xlabel("t")
    ax.set_ylabel("Amplitude")
    ax.grid(True, linestyle=":", linewidth=0.7)
    ax.legend(loc="best", frameon=True)

    fig.tight_layout()

    return {
        "reconstruction_{}".format(fmt): path
        for fmt, path in save_figure(
            fig,
            output_dir,
            "{}_reconstruction_{}".format(BASE_NAME, timestamp),
            formats,
        ).items()
    }


def plot_error(
    t,
    x_ref,
    x_hat_sod,
    x_hat_sinc,
    output_dir,
    timestamp,
    formats,
):
    """
    Plot dense-time reconstruction error.
    """
    fig, ax = plt.subplots(figsize=(10.0, 4.6))

    ax.plot(
        t,
        x_ref - x_hat_sod,
        linewidth=1.4,
        label="x(t) - SoD dense reconstruction",
    )

    ax.plot(
        t,
        x_ref - x_hat_sinc,
        linestyle="--",
        linewidth=1.4,
        label="x(t) - sinc_filter reconstruction",
    )

    ax.set_title("SoD reconstruction error")
    ax.set_xlabel("t")
    ax.set_ylabel("Error")
    ax.grid(True, linestyle=":", linewidth=0.7)
    ax.legend(loc="best", frameon=True)

    fig.tight_layout()

    return {
        "error_{}".format(fmt): path
        for fmt, path in save_figure(
            fig,
            output_dir,
            "{}_error_{}".format(BASE_NAME, timestamp),
            formats,
        ).items()
    }


def plot_channel_budget_panel(
    params,
    fdma_core,
    M_sod_per_sensor,
    event_count_per_sensor,
    sensor_index,
    payload_bits,
    available_bits,
    bits_per_event,
    transmit_event_times,
    output_dir,
    timestamp,
    formats,
):
    """
    Plot physical/channel-budget diagnostics.
    """
    B_per_sensor = fdma_core.get_bandwidth_per_sensor()
    snr_per_sensor = fdma_core.get_snr_per_sensor()
    snr_per_sensor_db = fdma_core.get_snr_per_sensor_db()
    capacity_per_sensor = fdma_core.get_capacity_per_sensor()

    text = (
        "SoD + FDMA debug budget\n"
        "-----------------------\n"
        "S                         = {}\n"
        "sensor_index              = {}\n"
        "B_total                   = {:.6e}\n"
        "B_sensor                  = {:.6e}\n"
        "P_per_sensor              = {:.6e}\n"
        "N0                        = {:.6e}\n"
        "SNR_sensor                = {:.6e}\n"
        "SNR_sensor_dB             = {:.6f}\n"
        "C_sensor                  = {:.6e} bit/s\n"
        "tau                       = {:.6e} s\n"
        "available_bits_per_tau    = {:.6e}\n"
        "event_count_per_sensor    = {}\n"
        "M_sod_per_sensor          = {}\n"
        "transmit_event_times      = {}\n"
        "amplitude_bits_per_event  = {:.6f}\n"
        "time_bits_per_event       = {:.6f}\n"
        "total_bits_per_event      = {:.6f}\n"
        "payload_bits              = {:.6e}\n"
        "payload_feasible          = {}\n"
    ).format(
        params.S,
        sensor_index,
        params.B,
        B_per_sensor[sensor_index],
        params.P,
        params.N0,
        snr_per_sensor[sensor_index],
        snr_per_sensor_db[sensor_index],
        capacity_per_sensor[sensor_index],
        params.tau,
        available_bits,
        np.asarray(event_count_per_sensor, dtype=int).tolist(),
        np.asarray(M_sod_per_sensor, dtype=int).tolist(),
        bool(transmit_event_times),
        bits_per_event["amplitude_bits"],
        bits_per_event["time_bits"],
        bits_per_event["total_bits"],
        payload_bits,
        bool(payload_bits <= available_bits),
    )

    fig, ax = plt.subplots(figsize=(8.8, 5.4))
    ax.text(
        0.02,
        0.98,
        text,
        transform=ax.transAxes,
        va="top",
        ha="left",
        family="monospace",
        fontsize=10,
    )
    ax.axis("off")

    fig.tight_layout()

    return {
        "channel_budget_{}".format(fmt): path
        for fmt, path in save_figure(
            fig,
            output_dir,
            "{}_channel_budget_{}".format(BASE_NAME, timestamp),
            formats,
        ).items()
    }


# =============================================================================
# MAIN RUNNER
# =============================================================================

def run_debug_sod_full_system(
    config_path: Optional[str] = None,
    show_plots: bool = False,
    B_value: Optional[float] = None,
    seed: Optional[int] = None,
    sensor_index: Optional[int] = None,
) -> Dict[str, Any]:
    """
    Run one complete SoD debug simulation.

    Parameters
    ----------
    config_path : str or None
        Path to YAML config. If None, default in-memory config is used.

    show_plots : bool
        If True, show figures interactively after saving.

    B_value : float or None
        Optional override for cfg["system"]["B"].

    seed : int or None
        Optional override for cfg["debug"]["seed"].

    sensor_index : int or None
        Optional override for cfg["debug"]["sensor_index"].

    Returns
    -------
    dict
        Debug outputs and generated file paths.
    """
    cfg = load_yaml_config(config_path)
    cfg = ensure_output_section(cfg)

    if B_value is not None:
        cfg["system"]["B"] = float(B_value)

    if seed is not None:
        if "debug" not in cfg:
            cfg["debug"] = {}
        cfg["debug"]["seed"] = int(seed)

    if sensor_index is not None:
        if "debug" not in cfg:
            cfg["debug"] = {}
        cfg["debug"]["sensor_index"] = int(sensor_index)

    output_dir, timestamp = prepare_output_dir(cfg)

    print("\n[SoD FULL SYSTEM DEBUG]")
    print("[INFO] output_dir =", output_dir)
    print("[INFO] timestamp  =", timestamp)

    rng_seed = int(cfg.get("debug", {}).get("seed", 42))
    rng = np.random.default_rng(rng_seed)

    params = build_derived_system_parameters(cfg)

    tau = float(params.tau)
    Tt = float(cfg["signal"]["Tt"])
    t = np.arange(0.0, tau, Tt)

    selected_sensor = int(cfg.get("debug", {}).get("sensor_index", 0))

    if selected_sensor < 0 or selected_sensor >= params.S:
        raise ValueError(
            "debug.sensor_index must be in [0, {}].".format(params.S - 1)
        )

    # -------------------------------------------------------------------------
    # Generate random, filtered, DC-removed, P2P-adjusted signals
    # -------------------------------------------------------------------------
    sig = generate_random_filtered_dc_p2p_signals(
        cfg=cfg,
        rng=rng,
        params=params,
        t=t,
    )

    x_raw = sig["x_raw"]
    x_filtered = sig["x_filtered"]
    x_no_dc = sig["x_no_dc"]
    x_ref = sig["x_ref"]
    dc_values = sig["dc_values"]
    p2p_scales = sig["p2p_scales"]

    x_ref_tensor = x_ref[:, None, :]

    # -------------------------------------------------------------------------
    # FDMA budget diagnostics from core
    # -------------------------------------------------------------------------
    fdma_core = FDMACore(
        S=params.S,
        B_total=params.B,
        P_per_sensor=params.P,
        tau=params.tau,
        bandwidth_allocation=params.bandwidth_allocation,
        N0=params.N0,
        normalize_sensor_power=True,
        return_nonorthogonal_sum_preview=False,
    )

    capacity_per_sensor = np.asarray(fdma_core.get_capacity_per_sensor(), dtype=float)
    available_bits_per_sensor = capacity_per_sensor * float(params.tau)
    available_bits = float(available_bits_per_sensor[selected_sensor])

    # -------------------------------------------------------------------------
    # SoD probe WITHOUT quantization.
    # This step determines the number of transmitted events.
    # -------------------------------------------------------------------------
    sod_cfg = cfg.get("sod", {})

    threshold = float(sod_cfg.get("threshold", 0.1))
    transmit_event_times = bool(sod_cfg.get("transmit_event_times", True))
    reconstruction_mode = str(sod_cfg.get("reconstruction_mode", "zero_order_hold"))
    initial_event = bool(sod_cfg.get("initial_event", True))
    periodic_replicas = int(sod_cfg.get("periodic_replicas", 10))

    sod_probe = SoDAcquisitionCore(
        threshold=threshold,
        initial_event=initial_event,
        reconstruction_mode=reconstruction_mode,
        transmit_event_times=transmit_event_times,
        quantize_amplitudes=False,
        quantize_times=False,
    )

    acq_probe = sod_probe.acquire(
        x=x_ref_tensor,
        t=t,
    )

    event_count_per_sensor = np.array([
        int(acq_probe.event_count["period_0_sensor_{}".format(s)])
        for s in range(params.S)
    ], dtype=int)

    # -------------------------------------------------------------------------
    # Compute SoD bins from capacity and event count using theory.py.
    # This is the correct adaptive-budget rule.
    # -------------------------------------------------------------------------
    M_sod_per_sensor = compute_M_sod_per_sensor(
        available_bits_per_sensor=available_bits_per_sensor,
        event_count_per_sensor=event_count_per_sensor,
        transmit_event_times=transmit_event_times,
        force_power_of_two=params.quantization_force_power_of_two,
        rounding_mode=params.quantization_rounding_mode,
    )

    # -------------------------------------------------------------------------
    # SoD acquisition WITH quantization.
    # If transmit_event_times=True, both event amplitude and event time use the
    # same M_sod per sensor. This is the symmetric field allocation.
    # -------------------------------------------------------------------------
    sod = SoDAcquisitionCore(
        threshold=threshold,
        initial_event=initial_event,
        reconstruction_mode=reconstruction_mode,
        transmit_event_times=transmit_event_times,
        quantize_amplitudes=True,
        amplitude_bins=M_sod_per_sensor,
        quantize_times=transmit_event_times,
        time_bins=(M_sod_per_sensor if transmit_event_times else None),
    )

    acq = sod.acquire(
        x=x_ref_tensor,
        t=t,
    )

    rec = sod.reconstruct(
        acquisition_result=acq,
        t_eval=t,
    )

    # -------------------------------------------------------------------------
    # Select sensor outputs
    # -------------------------------------------------------------------------
    key = "period_0_sensor_{}".format(selected_sensor)

    x_ref_selected = x_ref[:, selected_sensor]
    x_hat_sod = rec.reconstructed_signal[:, 0, selected_sensor]

    event_times_tx = acq.event_times[key]
    event_values_tx = acq.event_values[key]

    event_times_rx = (
        acq.event_times_quantized[key]
        if acq.event_times_quantized is not None
        else acq.event_times[key]
    )

    event_values_rx = (
        acq.event_values_quantized[key]
        if acq.event_values_quantized is not None
        else acq.event_values[key]
    )

    event_value_indices = (
        acq.event_value_indices[key]
        if acq.event_value_indices is not None
        else np.array([])
    )

    event_time_indices = (
        acq.event_time_indices[key]
        if acq.event_time_indices is not None
        else np.array([])
    )

    # -------------------------------------------------------------------------
    # sinc_filter from core
    # -------------------------------------------------------------------------
    x_hat_sinc_tensor = sinc_filter(
        rec.reconstructed_signal,
        BW=float(cfg["signal"].get("W", params.W)),
        Tt=Tt,
        Tth=float(periodic_replicas) * tau,
        x_clones=int(2 * periodic_replicas),
    )

    x_hat_sinc = x_hat_sinc_tensor[:, 0, selected_sensor]

    # -------------------------------------------------------------------------
    # Metrics
    # -------------------------------------------------------------------------
    mse_sod = _compute_mse(x_ref_selected, x_hat_sod)
    mse_sinc = _compute_mse(x_ref_selected, x_hat_sinc)

    event_count = int(acq.event_count[key])
    payload_bits = float(acq.payload_bits[key])
    bits_per_event = acq.payload_metadata["bits_per_event"][key]
    payload_feasible = bool(payload_bits <= available_bits)

    print("[INFO] seed                     =", rng_seed)
    print("[INFO] selected_sensor          =", selected_sensor)
    print("[INFO] threshold                =", threshold)
    print("[INFO] transmit_event_times     =", transmit_event_times)
    print("[INFO] event_count              =", event_count)
    print("[INFO] event_count_per_sensor   =", event_count_per_sensor)
    print("[INFO] available_bits           = {:.8e}".format(available_bits))
    print("[INFO] M_sod_per_sensor         =", M_sod_per_sensor)
    print("[INFO] bits_per_event           =", bits_per_event)
    print("[INFO] payload_bits             = {:.8e}".format(payload_bits))
    print("[INFO] payload_feasible         =", payload_feasible)
    print("[INFO] mse_sod                  = {:.8e}".format(mse_sod))
    print("[INFO] mse_sinc                 = {:.8e}".format(mse_sinc))

    # -------------------------------------------------------------------------
    # Save figures
    # -------------------------------------------------------------------------
    formats = figure_formats(cfg)
    generated_files = {}

    if cfg["output"].get("save_plot", True):
        generated_files.update(
            plot_signal_and_events(
                t=t,
                x_ref=x_ref_selected,
                event_times_tx=event_times_tx,
                event_values_tx=event_values_tx,
                event_times_rx=event_times_rx,
                event_values_rx=event_values_rx,
                sensor_index=selected_sensor,
                output_dir=output_dir,
                timestamp=timestamp,
                formats=formats,
            )
        )

        generated_files.update(
            plot_reconstruction(
                t=t,
                x_ref=x_ref_selected,
                x_hat_sod=x_hat_sod,
                x_hat_sinc=x_hat_sinc,
                mse_sod=mse_sod,
                mse_sinc=mse_sinc,
                output_dir=output_dir,
                timestamp=timestamp,
                formats=formats,
            )
        )

        generated_files.update(
            plot_error(
                t=t,
                x_ref=x_ref_selected,
                x_hat_sod=x_hat_sod,
                x_hat_sinc=x_hat_sinc,
                output_dir=output_dir,
                timestamp=timestamp,
                formats=formats,
            )
        )

        generated_files.update(
            plot_channel_budget_panel(
                params=params,
                fdma_core=fdma_core,
                M_sod_per_sensor=M_sod_per_sensor,
                event_count_per_sensor=event_count_per_sensor,
                sensor_index=selected_sensor,
                payload_bits=payload_bits,
                available_bits=available_bits,
                bits_per_event=bits_per_event,
                transmit_event_times=transmit_event_times,
                output_dir=output_dir,
                timestamp=timestamp,
                formats=formats,
            )
        )

    # -------------------------------------------------------------------------
    # Save arrays
    # -------------------------------------------------------------------------
    if cfg["output"].get("save_arrays", True):
        arrays_path = save_npz_payload(
            output_dir=output_dir,
            timestamp=timestamp,
            t=t,
            x_raw=x_raw,
            x_filtered=x_filtered,
            x_no_dc=x_no_dc,
            x_ref=x_ref,
            x_hat_sod_all=rec.reconstructed_signal[:, 0, :],
            x_hat_sinc_all=x_hat_sinc_tensor[:, 0, :],
            x_ref_selected=x_ref_selected,
            x_hat_sod=x_hat_sod,
            x_hat_sinc=x_hat_sinc,
            event_times_tx=event_times_tx,
            event_values_tx=event_values_tx,
            event_times_rx=event_times_rx,
            event_values_rx=event_values_rx,
            event_value_indices=event_value_indices,
            event_time_indices=event_time_indices,
            dc_values=dc_values,
            p2p_scales=p2p_scales,
            event_count_per_sensor=event_count_per_sensor,
            M_sod_per_sensor=np.asarray(M_sod_per_sensor, dtype=int),
            available_bits_per_sensor=available_bits_per_sensor,
            capacity_per_sensor=capacity_per_sensor,
        )
        generated_files["arrays_npz"] = arrays_path

    # -------------------------------------------------------------------------
    # Save config
    # -------------------------------------------------------------------------
    if cfg["output"].get("save_config_copy", True):
        config_copy = save_config_copy_or_dump(
            cfg=cfg,
            config_path=config_path,
            output_dir=output_dir,
            timestamp=timestamp,
        )
        generated_files["config"] = config_copy

    # -------------------------------------------------------------------------
    # Save metadata
    # -------------------------------------------------------------------------
    metadata = {
        "created_at": datetime.datetime.utcnow().replace(microsecond=0).isoformat() + "Z",
        "project_root": str(PROJECT_ROOT),
        "config_path": str(config_path) if config_path is not None else None,
        "output_dir": output_dir,
        "git_commit": get_git_commit(),
        "signal": {
            "distribution": cfg["signal"].get("distribution", "uniform"),
            "W": float(cfg["signal"].get("W", params.W)),
            "tau": float(params.tau),
            "Tt": float(Tt),
            "peak_to_peak": float(cfg["signal"].get("peak_to_peak", 0.0)),
            "dc_values": dc_values,
            "p2p_scales": p2p_scales,
        },
        "physical_model": {
            "S": int(params.S),
            "B_total": float(params.B),
            "P": float(params.P),
            "N0": float(params.N0),
            "bandwidth_allocation": np.asarray(params.bandwidth_allocation, dtype=float),
            "B_per_sensor": fdma_core.get_bandwidth_per_sensor(),
            "SNR_per_sensor": fdma_core.get_snr_per_sensor(),
            "SNR_per_sensor_dB": fdma_core.get_snr_per_sensor_db(),
            "capacity_per_sensor": fdma_core.get_capacity_per_sensor(),
            "available_bits_per_sensor": available_bits_per_sensor,
        },
        "sod_budget_rule": {
            "rule": (
                "M_sod is computed from available_bits_per_sensor and "
                "event_count_per_sensor using compute_M_sod_per_sensor(...)."
            ),
            "transmit_event_times": bool(transmit_event_times),
            "fields_per_event": 2 if transmit_event_times else 1,
            "event_count_per_sensor": event_count_per_sensor,
            "M_sod_per_sensor": np.asarray(M_sod_per_sensor, dtype=int),
        },
        "sod": {
            "threshold": float(threshold),
            "transmit_event_times": bool(transmit_event_times),
            "reconstruction_mode": reconstruction_mode,
            "initial_event": bool(initial_event),
            "amplitude_bins": sod.amplitude_bins,
            "time_bins": sod.time_bins,
            "selected_sensor": int(selected_sensor),
            "event_count": int(event_count),
            "payload_bits": float(payload_bits),
            "available_bits": float(available_bits),
            "payload_feasible": bool(payload_feasible),
            "bits_per_event": bits_per_event,
            "amplitude_quantization_metadata": acq.amplitude_quantization_metadata,
            "time_quantization_metadata": acq.time_quantization_metadata,
            "payload_metadata": acq.payload_metadata,
        },
        "metrics": {
            "mse_sod": float(mse_sod),
            "mse_sinc": float(mse_sinc),
        },
        "generated_files": generated_files,
    }

    if cfg["output"].get("save_metadata", True):
        metadata_path = save_metadata(
            metadata=metadata,
            output_dir=output_dir,
            timestamp=timestamp,
        )
        generated_files["metadata"] = metadata_path

    print("\n[INFO] Generated files:")
    for k, v in generated_files.items():
        print("       {}: {}".format(k, v))

    if show_plots:
        plt.show(block=True)
    else:
        plt.close("all")

    return {
        "cfg": cfg,
        "params": params,
        "fdma_core": fdma_core,
        "sod_probe": sod_probe,
        "sod": sod,
        "acq_probe": acq_probe,
        "acq": acq,
        "rec": rec,
        "t": t,
        "x_raw": x_raw,
        "x_filtered": x_filtered,
        "x_no_dc": x_no_dc,
        "x_ref": x_ref,
        "x_ref_selected": x_ref_selected,
        "x_hat_sod": x_hat_sod,
        "x_hat_sinc": x_hat_sinc,
        "event_times_tx": event_times_tx,
        "event_values_tx": event_values_tx,
        "event_times_rx": event_times_rx,
        "event_values_rx": event_values_rx,
        "event_value_indices": event_value_indices,
        "event_time_indices": event_time_indices,
        "event_count": event_count,
        "event_count_per_sensor": event_count_per_sensor,
        "M_sod_per_sensor": M_sod_per_sensor,
        "payload_bits": payload_bits,
        "available_bits": available_bits,
        "available_bits_per_sensor": available_bits_per_sensor,
        "payload_feasible": payload_feasible,
        "mse_sod": mse_sod,
        "mse_sinc": mse_sinc,
        "output_dir": output_dir,
        "timestamp": timestamp,
        "generated_files": generated_files,
    }


# =============================================================================
# CLI
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Run full-system SoD debug."
    )

    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help="Path to YAML config. If omitted, an in-memory default config is used.",
    )

    parser.add_argument(
        "--show",
        action="store_true",
        help="Show figures interactively after saving.",
    )

    parser.add_argument(
        "--B",
        type=float,
        default=None,
        help="Optional override for system.B.",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Optional override for debug.seed.",
    )

    parser.add_argument(
        "--sensor",
        type=int,
        default=None,
        help="Optional override for debug.sensor_index.",
    )

    args = parser.parse_args()

    run_debug_sod_full_system(
        config_path=args.config,
        show_plots=args.show,
        B_value=args.B,
        seed=args.seed,
        sensor_index=args.sensor,
    )


if __name__ == "__main__":
    main()
